### ISSUE TITLE
cannot link directly with dylib/framework

### ISSUE THREAD

**Issue by davepropelio** [Eyevinn/node-srt#10]
### Description
I created a new npm project and install ```npm install --save @eyevinn/srt```. It asked me to install cmake which i did. Everything gets built when ./configure ran until this error shows up.

- Macbook PRO
- macOS Catalina 10.15.3
-  NodeJS v10.20.1
- cmake version 3.18.1

```
Scanning dependencies of target srt_shared
[ 80%] Building C object CMakeFiles/srt_shared.dir/cmake_object_lib_support.c.o
[ 82%] Linking CXX shared library libsrt.dylib

/Users/johndavedecano/Projects/node-srt/node_modules/@eyevinn/srt/deps/srt/srtcore/fec.cpp:976:20: warning: unused function 'CellMark' [-Wunused-function]
static inline char CellMark(const std::deque<bool>& cells, int index)
                   ^
1 warning generated.
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsrt.1.4.1.dylib] Error 1
make[1]: *** [CMakeFiles/srt_shared.dir/all] Error 2
make: *** [all] Error 2

npm WARN srt@1.0.0 No description
npm WARN srt@1.0.0 No repository field.
```

**Comment by birme** [comment]
Thanks, I haven't seen this issue myself before. Will need to investigate.

**Comment by Morpheus235** [comment]
Same Issue here running Catalina 10.15.5. The Issue seems to be Apple not allowing to link to the system supplied Openssl library.
Resolved it by following this Issue/Guide on Stackoverflow.

https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib

**Comment by birme** [comment]
Thank you, I will write a note that it requires a newer version of openssl. Which version of openssl did you get it to work with. This one?
```
brew switch openssl 1.0.2q
```

**Comment by tchakabam** [comment]
You may also fix this issue with (given your brew install corresponds to this location):

```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
```
See what I wrote on: https://github.com/Eyevinn/node-srt/pull/14

**Comment by tchakabam** [comment]
^

In case you want to actually keep your up-to-date OpenSSL install from brew (or whereever), which is actually I think from a security point of view a *much* better idea ... :) 

Moreover, I think there is a breaking change between 1.0 and 1.1 (it doesn't make sense in terms of sem-ver, but basically some function that was de-facto public was made officially private, but that broke some apps using it afair - there is a way to fix that app-side obviously with a different now public functionality provided in 1.1). Just saying, if you downgrade you may be blocked to use latest versions of packages that migrated their usage to the 1.1 mode.
