### ISSUE TITLE
Incompatibility with newer version of SRT

### ISSUE THREAD

**Issue by amunhoz** [Eyevinn/node-srt#17]
It looks like the latest version of SRT is creating a problem with srt_accept, throwing a "bad parameter" error.
Did a test with a new build with the release zip of v1.4.1 and the problem disappeared.

Tested with Ubuntu 18.04 + Nodejs v14

**Comment by tchakabam** [comment]
Yes, I think this is what issues https://github.com/Eyevinn/node-srt/issues/16 & https://github.com/Eyevinn/node-srt/issues/15 are also about! :) 

Thanks for the more clear and concise report here on this.

Unfortunately haven't looked into this codebase for a bit, and we didn't have to deal with this issue in our prod case.

@amunhoz You can deal with the current way to just modify the used libSRT git tag in the build script? What do you suggest?

**Comment by tchakabam** [comment]
@amunhoz There is a fix ^
