### ISSUE TITLE
npm install --save @eyevinn/srt fails on MacOS 11.0

### ISSUE THREAD

**Issue by joedemax** [Eyevinn/node-srt#30]
Can anyone advise on this? I have many years of C# developement experience but this is my first time with NodeJS.

`joedemax@Joes-MacBook-Pro code % npm install --save @eyevinn/srt

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 2
npm ERR! path /Users/joedemax/code/node_modules/@eyevinn/srt
npm ERR! command failed
npm ERR! command sh -c npm run build-srt && npm run rebuild
npm ERR! > @eyevinn/srt@0.5.2 build-srt
npm ERR! > node scripts/build-srt-sdk.js
npm ERR! 
npm ERR! Creating dir: /Users/joedemax/code/node_modules/@eyevinn/srt/deps
npm ERR! Cloning https://github.com/Haivision/srt.git#v1.4.2
npm ERR! Building SRT SDK and prerequisites for current platform: darwin
npm ERR! Running ./configure
npm ERR! Running: cmake . -DCMAKE_INSTALL_PREFIX=/Users/joedemax/code/node_modules/@eyevinn/srt/deps/build -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.a
npm ERR! CONFIGURE: cmake reported error: couldn't execute "cmake": no such file or directory
npm ERR! Running make with threads: 8
npm ERR! make: *** No targets specified and no makefile found.  Stop.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joedemax/.npm/_logs/2021-08-17T14_46_34_723Z-debug.log`

**Comment by bwallberg** [comment]
Hi!
Have you installed the pre-requirements as defined in the readme?
See: https://github.com/Haivision/srt?ts=2#build-on-mac-darwin-ios

In short you need to have cmake & openssl installed and have the following environment variables set:
```
OPENSSL_ROOT_DIR
OPENSSL_LIB_DIR
OPENSSL_INCLUDE_DIR
```

For me though it was enough to do the following `OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ npm install @eyevinn/srt`.

We will look into including openssl automatically but installing them must still be done by you unfortunately.
