### ISSUE TITLE
Identify streams with streamID send from FFMPEG

### ISSUE THREAD

**Issue by ardianreqica** [Eyevinn/node-srt#33]
When I push a video in node-js srt project using ffmpeg, I can not find stream key or stream id to identify a particular stream, in order to make validations.
Is it possible to get streamID when I push the video using the command down below?
ffmpeg -f lavfi -re -i smptebars=duration=60:size=1280x720:rate=30 -f lavfi -re -i sine=frequency=1000:duration=60:sample_rate=44100 -pix_fmt yuv420p -c:v libx264 -b:v 1000k -g 30 -keyint_min 120 -profile:v baseline -preset veryfast -f mpegts "srt://127.0.0.1:1234?streamid=name&srt_streamid=namename"

**Comment by birme** [comment]
Thank you for reporting this. We would need to look into whether there are missing bindings in order to implement the following: https://github.com/Haivision/srt/blob/master/docs/features/access-control.md

**Comment by Morpheus235** [comment]
@birme @ardianreqica I added a [Pull Request](https://github.com/Eyevinn/node-srt/pull/34) implementing SRTO_STREAMID which allows it to be set and read on the socket.

**Comment by birme** [comment]
Thanks! Merged to master and will test it a bit myself before I create a release. Will close this ticket once that is done.

**Comment by Morpheus235** [comment]
No problem. Thanks for creating this awesome   library. Also using Int values is possible and results in wrong Chars. Probably since SRT expects a valid String and not Integers. Restricting that would be something to do probably. Maybe in the setSockopt call? I only stumbled upon this while testing.

**Comment by peykens** [comment]
Hi, did you get this working ?
I'm trying to setup a server to receive multiple feeds, identified by the streamid, but I'm always running into erors when I try to get the options after accept.

**Comment by birme** [comment]
We discovered an issue with the patch that was just now merged to master. I haven't verified it myself yet though.
