### ISSUE TITLE
node-srt installation problem

### ISSUE THREAD

**Issue by plustariq** [Eyevinn/node-srt#41]
I wanted to play video with srt protocol on the browser, but I didn't find a way to play it. After doing some research, I wanted to try @eyevinn/srt node package, but when I am trying to install, it produces this error.

```
$ npm install --save @eyevinn/srt
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be 
problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /home/tariq/temp/videoJsTest/node_modules/@eyevinn/srt
npm ERR! command failed
npm ERR! command sh /tmp/install-424c036d.sh
npm ERR! > @eyevinn/srt@0.6.0 build-srt
npm ERR! > node scripts/build-srt-sdk.js
npm ERR!
npm ERR! Creating dir: /home/tariq/temp/videoJsTest/node_modules/@eyevinn/srt/deps
npm ERR! Cloning https://github.com/Haivision/srt.git#v1.4.2
npm ERR! Building SRT SDK and prerequisites for current platform: linux
npm ERR! Running ./configure
npm ERR! /bin/sh: 1: ./configure: not found
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tariq/.npm/_logs/2022-07-26T10_17_03_085Z-debug-0.log
```

**Comment by birme** [comment]
There seems to be an issue when building the SRT library. Perhaps there are some packages missing in your linux-distribution. You could try cloning the SRT repo with the 1.4.2 tag and see if you can build it manually. Just to verify that it works.

However, if you plan to use SRT in the browser with this library it will not work. This library is an extension to NodeJS and does not compile into wasm or something you can load in your browser.

**Comment by plustariq** [comment]
> There seems to be an issue when building the SRT library. Perhaps there are some packages missing in your linux-distribution. You could try cloning the SRT repo with the 1.4.2 tag and see if you can build it manually. Just to verify that it works.
> 
> However, if you plan to use SRT in the browser with this library it will not work. This library is an extension to NodeJS and does not compile into wasm or something you can load in your browser.

thank you so much for your valuable comment. but is there any library to play real time video with (srt protocol) on the browser?

**Comment by birme** [comment]
.. 
> thank you so much for your valuable comment. but is there any library to play real time video with (srt protocol) on the browser?

Not that I am aware of.

**Comment by plustariq** [comment]
> ..
> 
> > thank you so much for your valuable comment. but is there any library to play real time video with (srt protocol) on the browser?
> 
> Not that I am aware of.

please tell me a way to play real time video with SRT protocol on the browser.

**Comment by birme** [comment]
> 
> please tell me a way to play real time video with SRT protocol on the browser.

As SRT is an extension to the UDP protocol it would require changes on a browser tech networking layer, which is something you cannot extend from a browser application. You would need to look into other protocols for realtime video playback in a browser. WebRTC is for example a candidate, or traditional HTTP based streaming protocols such as HLS and MPEG-DASH.
If you want a primer in video streaming (HTTP based) you can have a read here: https://eyevinntechnology.medium.com/internet-video-streaming-abr-part-1-b10964849e19

**Comment by plustariq** [comment]
> > please tell me a way to play real time video with SRT protocol on the browser.
> 
> As SRT is an extension to the UDP protocol it would require changes on a browser tech networking layer, which is something you cannot extend from a browser application. You would need to look into other protocols for realtime video playback in a browser. WebRTC is for example a candidate, or traditional HTTP based streaming protocols such as HLS and MPEG-DASH. If you want a primer in video streaming (HTTP based) you can have a read here: https://eyevinntechnology.medium.com/internet-video-streaming-abr-part-1-b10964849e19

thank you so much🤍
