### ISSUE TITLE
using srtreadstream like with srt connection

### ISSUE THREAD

**Issue by bander-saeed94** [Eyevinn/node-srt#56]
How can I use SrtReadStream with SrtConnection instead of using the onClientData function?

**Comment by birme** [comment]
Hi!
Sorry for the delayed response. This one slipped. However, not sure I fully understand the question here.

The SRTReadStream is a high-level implementation and works for many cases, however if you are looking for some performance you would need to go down a level and use the AsyncSRT class and the `AsyncReaderWriter` to read/write chunks on a connection.

**Comment by bander-saeed94** [comment]
thanks I have used asyncSrtServer .

```
const reader = connection.getReaderWriter();
   const chunks = await reader.readChunks();
 connection.on("data", async () => {
    onClientData();
  });
async function onClientData() {
    const chunks = await reader.readChunks();
    chunks.forEach(item => readableStream.push(item))
    // console.log(chunks[0])
  }

```
