### ISSUE TITLE
windows install failed

### ISSUE THREAD

**Issue by MarsTsaiCoding** [Eyevinn/node-srt#8]
Well done, this is a useful tool
But when I use windows to **npm install --save @eyevinn/srt** it fails
![image](https://user-images.githubusercontent.com/14837356/89632499-de273800-d8d4-11ea-9f61-73fb8aaf4ffc.png)

**Comment by birme** [comment]
I think, in this case, you need to run npm init first

**Comment by tchakabam** [comment]
Hi @MarsCaiWORD! 

I didn't test this on Windows myself, but can you give it a try with my current patch? I think I managed to fix something in how the package got installed. -> https://github.com/Eyevinn/node-srt/pull/9 (or checkout https://github.com/emliri/node-srt/tree/develop)

It is true what @birme says, that the current version will not work without an initial package.json created somewhere. I think this patch may help as I doesn't use the preinstall hook anymore, but will first install all package deps (properly install the package), and then runs the `install` hook which simply will run the SRT SDK build script (which I hope will also still work on Windows after my changes - afaiu it should, would be great if you can test) & finally the node-gyp tool that will build our node add-on. 

@birme Please let me know if I missed something or give feedback on the PR, maybe things were like this for a reason I ignore. Cheers :)

**Comment by MarsTsaiCoding** [comment]
@birme  I tried it,  same problem
@tchakabam  Sorry i'm not a professional how can i do it

**Comment by tchakabam** [comment]
Well, I guess you'd just need to add `git@github.com:emliri/node-srt.git` as a git remote, for example on the command-line with: `git remote add emliri git@github.com:emliri/node-srt.git` and then you could do `git fetch emliri` and then `git checkout emliri/develop`. I guess that should work anywhere. Do `git remote remove emliri` to get rid of it again if you need. You might need to stash uncommited changes before the checkout.

**Comment by Llorx** [comment]
When compiling using vstudio 2019 returns these errors (Google translated, but you get the point):

```
d:\dropbox\node.js\rtmp-server\node-srt\src\node-srt.cc (393): error C2131: expression was not evaluated as a constant [D:\Dropbox\node.js\rtmp-server\node-srt\build\node_srt.vcxproj]
d:\dropbox\node.js\rtmp-server\node-srt\src\node-srt.cc (393): note: the error was due to a variable read out of its lifetime
d:\dropbox\node.js\rtmp-server\node-srt\src\node-srt.cc (393): note: see usage of 'fdsSetSize'
d:\dropbox\node.js\rtmp-server\node-srt\src\node-srt.cc (398): error C2660: 'Napi :: Number :: New': function does not accept 1 arguments [D:\Dropbox\node.js\rtmp-server\node-srt\build\node_srt.vcxproj]
d:\dropbox\node.js\rtmp-server\node-srt\node_modules\node-addon-api\napi-inl.h (601): note: see declaration of 'Napi :: Number :: New' (compiling source file ..\src\node-srt.cc)
```

I'm not sure what is happening :-(

EDIT: Created PR: https://github.com/Eyevinn/node-srt/pull/11

**Comment by tchakabam** [comment]
Thanks for the PR @Llorx ! (you will need to wait for @birme about merging that)

Interesting, seems that MSVC compiler has different rules here than GCC or Clang. 

Just wondering, how/why do you use VS to build this?

**Comment by Llorx** [comment]
Actually cmake prepares a vstudio project. Also the build script (scripts/build-srt-sdk.js https://github.com/Eyevinn/node-srt/pull/2) has explicitly set vstudio 2019. Is my C++ development environment in my computer, so...

**Comment by tchakabam** [comment]
I see, good to know it works like that out of the box then ✌️
